// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// User Login
type LoginRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LoginResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginResponse) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *LoginResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

// User Register
type RegisterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Gender               int32    `protobuf:"varint,2,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *RegisterRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RegisterResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterResponse) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *RegisterResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

// User Info
type UserInfoRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(m, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserInfoResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Mobile               string   `protobuf:"bytes,4,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfoResponse) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *UserInfoResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "user.RegisterResponse")
	proto.RegisterType((*UserInfoRequest)(nil), "user.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "user.UserInfoResponse")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0x27, 0x6d, 0x56, 0xea, 0x43, 0x9d, 0x3c, 0x71, 0x94, 0x9e, 0x66, 0x4f, 0x3b, 0x55, 0xd1,
	0x93, 0xd7, 0x5d, 0xa4, 0xa0, 0x22, 0x01, 0x2f, 0xde, 0x36, 0xfb, 0x36, 0x0a, 0xda, 0x6c, 0x49,
	0x87, 0xdf, 0xca, 0xcf, 0x28, 0x89, 0x89, 0xad, 0xc1, 0x1d, 0x77, 0xcb, 0x4b, 0xf2, 0xfb, 0xf7,
	0xde, 0x03, 0xd8, 0x69, 0x52, 0xe5, 0x46, 0xc9, 0x4e, 0x22, 0x37, 0xe7, 0x62, 0x0e, 0xc7, 0x0f,
	0x72, 0xdd, 0xb4, 0x82, 0xb6, 0x3b, 0xd2, 0x1d, 0x4e, 0x20, 0x79, 0x94, 0xcb, 0xe6, 0x9d, 0x32,
	0x36, 0x65, 0xb3, 0x23, 0xe1, 0x2a, 0xcc, 0x21, 0x7d, 0x5e, 0x68, 0xfd, 0x29, 0x55, 0x9d, 0x45,
	0xf6, 0xe5, 0xb7, 0x2e, 0xde, 0xe0, 0xc4, 0x71, 0xe8, 0x8d, 0x6c, 0x35, 0xe1, 0x29, 0x44, 0x55,
	0x6d, 0x09, 0x62, 0x11, 0x55, 0x35, 0x22, 0xf0, 0xa7, 0xc5, 0x07, 0x39, 0xa0, 0x3d, 0x1b, 0xa1,
	0x7b, 0x6a, 0x6b, 0x52, 0x59, 0x3c, 0x65, 0xb3, 0x91, 0x70, 0xd5, 0xc0, 0x00, 0x1f, 0x1a, 0x28,
	0xb6, 0x30, 0x16, 0xb4, 0x6e, 0x74, 0x47, 0xca, 0x7b, 0xf5, 0xb4, 0xec, 0x5f, 0xda, 0x68, 0x0f,
	0x6d, 0xbc, 0x37, 0x17, 0x0f, 0x72, 0xad, 0xe0, 0xac, 0x97, 0x3c, 0x60, 0xb4, 0x4b, 0x18, 0xbf,
	0x68, 0x52, 0x55, 0xbb, 0x92, 0x3e, 0x5a, 0x20, 0x63, 0xac, 0xf4, 0x5f, 0x0e, 0x67, 0xe5, 0xe6,
	0x8b, 0x01, 0x37, 0x42, 0x78, 0x0d, 0x23, 0x3b, 0x53, 0xc4, 0xd2, 0xee, 0xcc, 0x70, 0x49, 0xf2,
	0xf3, 0x3f, 0x77, 0xce, 0xce, 0x1d, 0xa4, 0xbe, 0x5b, 0x78, 0xf1, 0xf3, 0x21, 0x18, 0x58, 0x3e,
	0x09, 0xaf, 0x7b, 0xa8, 0x4f, 0xe7, 0xa1, 0x41, 0x43, 0x3c, 0x34, 0x6c, 0xc2, 0x3c, 0x7d, 0x4d,
	0xca, 0x2b, 0xf3, 0xb4, 0x4c, 0xec, 0x5a, 0xdf, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x53,
	0x18, 0x1e, 0xe4, 0x02, 0x00, 0x00,
}
