// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pay.proto

package pay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// payment create
type CreateRequest struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Oid                  uint64   `protobuf:"varint,2,opt,name=Oid,proto3" json:"Oid,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CreateRequest) GetOid() uint64 {
	if m != nil {
		return m.Oid
	}
	return 0
}

func (m *CreateRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type CreateResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// payment detail
type DetailRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailRequest) Reset()         { *m = DetailRequest{} }
func (m *DetailRequest) String() string { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()    {}
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{2}
}

func (m *DetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailRequest.Unmarshal(m, b)
}
func (m *DetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailRequest.Marshal(b, m, deterministic)
}
func (m *DetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailRequest.Merge(m, src)
}
func (m *DetailRequest) XXX_Size() int {
	return xxx_messageInfo_DetailRequest.Size(m)
}
func (m *DetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetailRequest proto.InternalMessageInfo

func (m *DetailRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DetailResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Oid                  uint64   `protobuf:"varint,3,opt,name=Oid,proto3" json:"Oid,omitempty"`
	Amount               uint64   `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Source               uint64   `protobuf:"varint,5,opt,name=Source,proto3" json:"Source,omitempty"`
	Status               uint64   `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetailResponse) Reset()         { *m = DetailResponse{} }
func (m *DetailResponse) String() string { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()    {}
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{3}
}

func (m *DetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetailResponse.Unmarshal(m, b)
}
func (m *DetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetailResponse.Marshal(b, m, deterministic)
}
func (m *DetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetailResponse.Merge(m, src)
}
func (m *DetailResponse) XXX_Size() int {
	return xxx_messageInfo_DetailResponse.Size(m)
}
func (m *DetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetailResponse proto.InternalMessageInfo

func (m *DetailResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DetailResponse) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *DetailResponse) GetOid() uint64 {
	if m != nil {
		return m.Oid
	}
	return 0
}

func (m *DetailResponse) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *DetailResponse) GetSource() uint64 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *DetailResponse) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

// payment callback
type CallbackRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Oid                  uint64   `protobuf:"varint,3,opt,name=Oid,proto3" json:"Oid,omitempty"`
	Amount               uint64   `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Source               uint64   `protobuf:"varint,5,opt,name=Source,proto3" json:"Source,omitempty"`
	Status               uint64   `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackRequest) Reset()         { *m = CallbackRequest{} }
func (m *CallbackRequest) String() string { return proto.CompactTextString(m) }
func (*CallbackRequest) ProtoMessage()    {}
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{4}
}

func (m *CallbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackRequest.Unmarshal(m, b)
}
func (m *CallbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackRequest.Marshal(b, m, deterministic)
}
func (m *CallbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackRequest.Merge(m, src)
}
func (m *CallbackRequest) XXX_Size() int {
	return xxx_messageInfo_CallbackRequest.Size(m)
}
func (m *CallbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackRequest proto.InternalMessageInfo

func (m *CallbackRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CallbackRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CallbackRequest) GetOid() uint64 {
	if m != nil {
		return m.Oid
	}
	return 0
}

func (m *CallbackRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CallbackRequest) GetSource() uint64 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *CallbackRequest) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type CallbackResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallbackResponse) Reset()         { *m = CallbackResponse{} }
func (m *CallbackResponse) String() string { return proto.CompactTextString(m) }
func (*CallbackResponse) ProtoMessage()    {}
func (*CallbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{5}
}

func (m *CallbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallbackResponse.Unmarshal(m, b)
}
func (m *CallbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallbackResponse.Marshal(b, m, deterministic)
}
func (m *CallbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallbackResponse.Merge(m, src)
}
func (m *CallbackResponse) XXX_Size() int {
	return xxx_messageInfo_CallbackResponse.Size(m)
}
func (m *CallbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CallbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CallbackResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateRequest)(nil), "pay.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "pay.CreateResponse")
	proto.RegisterType((*DetailRequest)(nil), "pay.DetailRequest")
	proto.RegisterType((*DetailResponse)(nil), "pay.DetailResponse")
	proto.RegisterType((*CallbackRequest)(nil), "pay.CallbackRequest")
	proto.RegisterType((*CallbackResponse)(nil), "pay.CallbackResponse")
}

func init() {
	proto.RegisterFile("pay.proto", fileDescriptor_0564d675d5c516e0)
}

var fileDescriptor_0564d675d5c516e0 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0x95, 0xb8, 0x35, 0x70, 0x52, 0x43, 0x75, 0xfc, 0x91, 0xd5, 0x85, 0x2a, 0x13, 0x53,
	0x50, 0x61, 0x60, 0x86, 0xb2, 0x54, 0x0c, 0x45, 0x45, 0x2c, 0x6c, 0xd7, 0xc6, 0x43, 0x44, 0xa8,
	0x4d, 0xe2, 0x0c, 0x79, 0x07, 0x78, 0x0b, 0x1e, 0x14, 0x25, 0xb6, 0x05, 0x09, 0x65, 0x65, 0xcb,
	0x7d, 0xba, 0xbb, 0x7c, 0xfa, 0x9d, 0xe1, 0x40, 0x53, 0x9d, 0xe8, 0x42, 0x19, 0x85, 0x4c, 0x53,
	0x1d, 0xdf, 0xc3, 0x68, 0x5e, 0x48, 0x32, 0x72, 0x25, 0xdf, 0x2a, 0x59, 0x1a, 0x1c, 0x03, 0x7b,
	0xca, 0x52, 0x11, 0x4c, 0x83, 0xf3, 0xc1, 0xaa, 0xf9, 0x6c, 0xc8, 0x32, 0x4b, 0x45, 0x68, 0xc9,
	0x32, 0x4b, 0xf1, 0x14, 0xf8, 0xcd, 0xab, 0xaa, 0xb6, 0x46, 0xb0, 0x16, 0xba, 0x2a, 0x9e, 0x42,
	0xe4, 0x97, 0x95, 0x5a, 0x6d, 0x4b, 0x89, 0x11, 0x84, 0x0b, 0xbf, 0x2c, 0x5c, 0xa4, 0xf1, 0x19,
	0x8c, 0xee, 0xa4, 0xa1, 0x2c, 0xf7, 0xbf, 0xeb, 0x37, 0xbc, 0x07, 0x10, 0xf9, 0x8e, 0xdd, 0x3b,
	0xbc, 0x61, 0xf8, 0xcb, 0x90, 0xed, 0x32, 0x1c, 0xfc, 0x34, 0x6c, 0xf8, 0xa3, 0xaa, 0x8a, 0x8d,
	0x14, 0x43, 0xcb, 0x6d, 0xd5, 0x72, 0x43, 0xa6, 0x2a, 0x05, 0x77, 0xbc, 0xad, 0xe2, 0x8f, 0x00,
	0x0e, 0xe7, 0x94, 0xe7, 0x6b, 0xda, 0xbc, 0xfc, 0xa1, 0xfc, 0xaf, 0x3e, 0x08, 0xe3, 0x6f, 0x1d,
	0x9b, 0xcf, 0xe5, 0x67, 0x00, 0xec, 0x81, 0x6a, 0x9c, 0x01, 0xb7, 0xe9, 0x23, 0x26, 0xcd, 0x95,
	0x3b, 0x77, 0x9d, 0x1c, 0x75, 0x98, 0x8b, 0x76, 0x06, 0xdc, 0x86, 0xed, 0x46, 0x3a, 0xb7, 0x71,
	0x23, 0xbd, 0x6b, 0x5c, 0xc3, 0xbe, 0x37, 0xc0, 0x63, 0xbb, 0xb3, 0x9b, 0xcf, 0xe4, 0xa4, 0x47,
	0xed, 0xe0, 0xed, 0xde, 0xf3, 0x30, 0xb9, 0xd0, 0x54, 0xaf, 0x79, 0xfb, 0xfc, 0xae, 0xbe, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x97, 0xf1, 0xc1, 0x8d, 0x8b, 0x02, 0x00, 0x00,
}
